services:
  azureeventgridsimulator:
    image: azureeventgridsimulator:dev
    container_name: azureeventgridsimulator-dev
    ports:
      # add a port mapping for each topic in the settings file
      - "60101:60101"
    volumes:
      # map a local folder './docker' to a read-only folder '/aegs' in the container
      # this allows us to access files (e.g. settings or certificates) from within the container
      - ./docker:/aegs:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # specify cert details note: can be generated like so:
      # dotnet dev-certs https --export-path ./docker/azureEventGridSimulator.pfx --password Y0urSup3rCrypt1cPa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aegs/azureEventGridSimulator.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Y0urSup3rCrypt1cPa55w0rd!

      # you could also define topics/subscribers via via a configfile
      - AEGS_ConfigFile=/aegs/appsettings.docker.json

      # logging configuration
      - AEGS_Serilog__MinimumLevel__Default=Verbose

    depends_on:
      - servicebus-emulator

    networks:
      - aegs-network

    build:
      context: .
      dockerfile: ./Dockerfile

  # Azure Service Bus Emulator
  # See: https://learn.microsoft.com/en-us/azure/service-bus-messaging/test-locally-with-service-bus-emulator
  servicebus-emulator:
    container_name: servicebus-emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - ./docker/servicebus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"   # AMQP port
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-YourStr0ngP@ssword!}
      ACCEPT_EULA: "Y"
    depends_on:
      - mssql
    networks:
      aegs-network:
        aliases:
          - servicebus-emulator

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-YourStr0ngP@ssword!}
    networks:
      aegs-network:
        aliases:
          - mssql

networks:
  aegs-network:

volumes:
  docker:
