<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <Target
    Name="CSharpier"
    BeforeTargets="BeforeBuild"
    Condition="'$(DesignTimeBuild)' != 'true' And '$(MSBuildProjectName)' == 'AzureEventGridSimulator' And '$(TargetFramework)' == 'net10.0'"
  >
    <Exec
      Command="dotnet tool restore"
      WorkingDirectory="$(MSBuildThisFileDirectory).."
      StandardOutputImportance="low"
      StandardErrorImportance="low"
      ContinueOnError="true"
    />
    <Exec
      Command="dotnet tool run csharpier format src"
      WorkingDirectory="$(MSBuildThisFileDirectory).."
      StandardOutputImportance="low"
    />
  </Target>

  <Target
    Name="ConfigureGitHooks"
    BeforeTargets="BeforeBuild"
    Condition="'$(DesignTimeBuild)' != 'true' And '$(MSBuildProjectName)' == 'AzureEventGridSimulator' And '$(TargetFramework)' == 'net10.0' And Exists('$(MSBuildThisFileDirectory)../.git') And '$(CI)' != 'true'"
  >
    <Exec
      Command="git config core.hooksPath .githooks"
      WorkingDirectory="$(MSBuildThisFileDirectory).."
      StandardOutputImportance="low"
      StandardErrorImportance="low"
      ContinueOnError="true"
    />
  </Target>
</Project>
